---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - copy:
         src: urgenaccess
         dest: /home/ubuntu/.ssh/id_rsa
         owner: ubuntu
         group: ubuntu
         mode: 0600
